package com.example.spring_ecom.controller.api.admin.product;

import com.example.spring_ecom.controller.api.product.model.CreateProductRequest;
import com.example.spring_ecom.controller.api.product.model.ProductResponse;
import com.example.spring_ecom.controller.api.product.model.UpdateProductRequest;
import com.example.spring_ecom.core.response.ApiResponse;
import com.example.spring_ecom.core.response.ResponseCode;
import com.example.spring_ecom.domain.product.Product;
import com.example.spring_ecom.service.product.ProductQueryService;
import com.example.spring_ecom.service.product.ProductUseCase;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;

import java.math.BigDecimal;
import java.util.Objects;

/**
 * Trực tiếp truy xuất DB, không qua gRPC
 */
@RestController
@RequestMapping("/v1/api/admin/products")
@RequiredArgsConstructor
@Slf4j
@Tag(name = "Admin Product Management", description = "Admin APIs for managing books/products")
public class AdminProductController {

    private final ProductUseCase productUseCase;
    private final ProductQueryService productQueryService;

    @Operation(summary = "Get all products", description = "Get paginated list of all products (Admin only)")
    @GetMapping
    public ResponseEntity<ApiResponse<Page<ProductResponse>>> getAllProducts(
            Pageable pageable,
            @Parameter(description = "Search term") @RequestParam(required = false) String search,
            @Parameter(description = "Filter by category") @RequestParam(required = false) Long categoryId,
            @Parameter(description = "Filter by active status") @RequestParam(required = false) Boolean isActive) {
        try {
            log.info("Admin getting all products with pagination");
            Page<Product> products;
            if (Objects.nonNull(search) && !search.isBlank()) {
                products = productUseCase.searchProducts(search, pageable);
            } else {
                products = productUseCase.findAll(pageable);
            }
            Page<ProductResponse> response = productQueryService.toProductResponsePage(products);
            return ResponseEntity.ok(ApiResponse.Success.of(response));
        } catch (Exception e) {
            log.error("Error getting all products: {}", e.getMessage(), e);
            return ResponseEntity.internalServerError()
                    .body(ApiResponse.Error.of(ResponseCode.INTERNAL_SERVER_ERROR, "Failed to get products"));
        }
    }

    @Operation(summary = "Get product by ID", description = "Get product detail by ID (Admin only)")
    @GetMapping("/{productId}")
    public ResponseEntity<ApiResponse<ProductResponse>> getProductById(
            @Parameter(description = "Product ID") @PathVariable Long productId) {
        try {
            log.info("Admin getting product by ID: {}", productId);
            return productUseCase.findById(productId)
                    .map(product -> ResponseEntity.ok(ApiResponse.Success.of(productQueryService.toProductResponse(product))))
                    .orElse(ResponseEntity.notFound().build());
        } catch (Exception e) {
            log.error("Error getting product: {}", e.getMessage(), e);
            return ResponseEntity.internalServerError()
                    .body(ApiResponse.Error.of(ResponseCode.INTERNAL_SERVER_ERROR, "Failed to get product"));
        }
    }

    @Operation(summary = "Create product", description = "Create new book/product (Admin only)")
    @PostMapping
    public ResponseEntity<ApiResponse<ProductResponse>> createProduct(
            @Valid @RequestBody CreateProductRequest request) {
        try {
            log.info("Admin creating new product: {}", request.getTitle());
            Product product = new Product(
                    null,
                    request.getTitle(),
                    null, // slug will be generated by service
                    request.getAuthor(),
                    request.getPublisher(),
                    request.getPublicationYear(),
                    Objects.nonNull(request.getLanguage()) ? request.getLanguage() : "Vietnamese",
                    request.getPages(),
                    Objects.nonNull(request.getFormat()) ? request.getFormat() : "Paperback",
                    request.getDescription(),
                    request.getPrice(),
                    request.getDiscountPrice(),
                    BigDecimal.ZERO, // costPrice
                    Objects.nonNull(request.getStockQuantity()) ? request.getStockQuantity() : 0,
                    request.getCoverImageUrl(),
                    Objects.nonNull(request.getIsBestseller()) ? request.getIsBestseller() : false,
                    Objects.nonNull(request.getIsActive()) ? request.getIsActive() : true,
                    0,
                    0,
                    BigDecimal.ZERO,
                    0,
                    null,
                    null,
                    null,
                    request.getCategoryId()
            );
            return productUseCase.create(product)
                    .map(created -> ResponseEntity.ok(
                            ApiResponse.Success.of(ResponseCode.CREATED, "Product created successfully",
                                    productQueryService.toProductResponse(created))))
                    .orElse(ResponseEntity.internalServerError()
                            .body(ApiResponse.Error.of(ResponseCode.INTERNAL_SERVER_ERROR, "Failed to create product")));
        } catch (Exception e) {
            log.error("Error creating product: {}", e.getMessage(), e);
            return ResponseEntity.internalServerError()
                    .body(ApiResponse.Error.of(ResponseCode.INTERNAL_SERVER_ERROR, "Failed to create product: " + e.getMessage()));
        }
    }

    @Operation(summary = "Update product", description = "Update existing product (Admin only)")
    @PutMapping("/{productId}")
    public ResponseEntity<ApiResponse<ProductResponse>> updateProduct(
            @Parameter(description = "Product ID") @PathVariable Long productId,
            @Valid @RequestBody UpdateProductRequest request) {
        try {
            log.info("Admin updating product: {}", productId);
            Product existing = productUseCase.findById(productId)
                    .orElseThrow(() -> new RuntimeException("Product not found with id: " + productId));

            Product updated = new Product(
                    existing.id(),
                    Objects.nonNull(request.getTitle()) ? request.getTitle() : existing.title(),
                    existing.slug(),
                    Objects.nonNull(request.getAuthor()) ? request.getAuthor() : existing.author(),
                    Objects.nonNull(request.getPublisher()) ? request.getPublisher() : existing.publisher(),
                    Objects.nonNull(request.getPublicationYear()) ? request.getPublicationYear() : existing.publicationYear(),
                    Objects.nonNull(request.getLanguage()) ? request.getLanguage() : existing.language(),
                    Objects.nonNull(request.getPages()) ? request.getPages() : existing.pages(),
                    Objects.nonNull(request.getFormat()) ? request.getFormat() : existing.format(),
                    Objects.nonNull(request.getDescription()) ? request.getDescription() : existing.description(),
                    Objects.nonNull(request.getPrice()) ? request.getPrice() : existing.price(),
                    Objects.nonNull(request.getDiscountPrice()) ? request.getDiscountPrice() : existing.discountPrice(),
                    existing.costPrice(),
                    Objects.nonNull(request.getStockQuantity()) ? request.getStockQuantity() : existing.stockQuantity(),
                    Objects.nonNull(request.getCoverImageUrl()) ? request.getCoverImageUrl() : existing.coverImageUrl(),
                    Objects.nonNull(request.getIsBestseller()) ? request.getIsBestseller() : existing.isBestseller(),
                    Objects.nonNull(request.getIsActive()) ? request.getIsActive() : existing.isActive(),
                    existing.viewCount(),
                    existing.soldCount(),
                    existing.ratingAverage(),
                    existing.ratingCount(),
                    existing.createdAt(),
                    null,
                    existing.deletedAt(),
                    Objects.nonNull(request.getCategoryId()) ? request.getCategoryId() : existing.categoryId()
            );

            return productUseCase.update(productId, updated)
                    .map(result -> ResponseEntity.ok(
                            ApiResponse.Success.of(ResponseCode.OK, "Product updated successfully",
                                    productQueryService.toProductResponse(result))))
                    .orElse(ResponseEntity.internalServerError()
                            .body(ApiResponse.Error.of(ResponseCode.INTERNAL_SERVER_ERROR, "Failed to update product")));
        } catch (Exception e) {
            log.error("Error updating product: {}", e.getMessage(), e);
            return ResponseEntity.internalServerError()
                    .body(ApiResponse.Error.of(ResponseCode.INTERNAL_SERVER_ERROR, "Failed to update product: " + e.getMessage()));
        }
    }

    @Operation(summary = "Delete product", description = "Soft delete product (Admin only)")
    @DeleteMapping("/{productId}")
    public ResponseEntity<ApiResponse<Void>> deleteProduct(
            @Parameter(description = "Product ID") @PathVariable Long productId) {
        try {
            log.info("Admin deleting product: {}", productId);
            productUseCase.delete(productId);
            return ResponseEntity.ok(ApiResponse.Success.of(ResponseCode.OK, "Product deleted successfully", null));
        } catch (Exception e) {
            log.error("Error deleting product: {}", e.getMessage(), e);
            return ResponseEntity.internalServerError()
                    .body(ApiResponse.Error.of(ResponseCode.INTERNAL_SERVER_ERROR, "Failed to delete product"));
        }
    }

    @Operation(summary = "Update product stock", description = "Update product stock quantity (Admin only)")
    @PutMapping("/{productId}/stock")
    public ResponseEntity<ApiResponse<ProductResponse>> updateProductStock(
            @Parameter(description = "Product ID") @PathVariable Long productId,
            @RequestParam int stockQuantity) {
        try {
            log.info("Admin updating stock for product: {}, quantity: {}", productId, stockQuantity);
            Product existing = productUseCase.findById(productId)
                    .orElseThrow(() -> new RuntimeException("Product not found with id: " + productId));

            Product updated = new Product(
                    existing.id(), existing.title(), existing.slug(), existing.author(),
                    existing.publisher(), existing.publicationYear(), existing.language(),
                    existing.pages(), existing.format(), existing.description(),
                    existing.price(), existing.discountPrice(), existing.costPrice(), stockQuantity,
                    existing.coverImageUrl(), existing.isBestseller(), existing.isActive(),
                    existing.viewCount(), existing.soldCount(), existing.ratingAverage(),
                    existing.ratingCount(), existing.createdAt(), null, existing.deletedAt(),
                    existing.categoryId()
            );

            return productUseCase.update(productId, updated)
                    .map(result -> ResponseEntity.ok(
                            ApiResponse.Success.of(ResponseCode.OK, "Stock updated successfully",
                                    productQueryService.toProductResponse(result))))
                    .orElse(ResponseEntity.internalServerError()
                            .body(ApiResponse.Error.of(ResponseCode.INTERNAL_SERVER_ERROR, "Failed to update stock")));
        } catch (Exception e) {
            log.error("Error updating product stock: {}", e.getMessage(), e);
            return ResponseEntity.internalServerError()
                    .body(ApiResponse.Error.of(ResponseCode.INTERNAL_SERVER_ERROR, "Failed to update stock"));
        }
    }
}
