package com.example.spring_ecom.repository.database.review;

import com.example.spring_ecom.config.MapStructGlobalConfig;
import com.example.spring_ecom.core.mapper.BaseEntityMapper;
import com.example.spring_ecom.domain.review.ProductReview;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;

@Mapper(config = MapStructGlobalConfig.class)
public interface ProductReviewEntityMapper extends BaseEntityMapper<ProductReview, ProductReviewEntity> {
    
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    @Mapping(target = "deletedAt", ignore = true)
    @Mapping(target = "isVerifiedPurchase", ignore = true)
    @Mapping(target = "likeCount", ignore = true)
    @Mapping(target = "dislikeCount", ignore = true)
    @Mapping(target = "adminReply", ignore = true)
    @Mapping(target = "adminReplyAt", ignore = true)
    @Mapping(target = "adminId", ignore = true)
    @Mapping(target = "rating", source = "domain.rating")
    @Mapping(target = "title", source = "domain.title")
    @Mapping(target = "comment", source = "domain.comment")
    void updateFromDomain(@MappingTarget ProductReviewEntity entity, ProductReview domain);
    
    @Mapping(target = "deletedAt", expression = "java(java.time.LocalDateTime.now())")
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "productId", ignore = true)
    @Mapping(target = "userId", ignore = true)
    @Mapping(target = "rating", ignore = true)
    @Mapping(target = "title", ignore = true)
    @Mapping(target = "comment", ignore = true)
    @Mapping(target = "isVerifiedPurchase", ignore = true)
    @Mapping(target = "likeCount", ignore = true)
    @Mapping(target = "dislikeCount", ignore = true)
    @Mapping(target = "adminReply", ignore = true)
    @Mapping(target = "adminReplyAt", ignore = true)
    @Mapping(target = "adminId", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    void markAsDeleted(@MappingTarget ProductReviewEntity entity, ProductReview ignored);
    
    @Mapping(target = "adminReply", source = "reply")
    @Mapping(target = "adminId", source = "adminId")
    @Mapping(target = "adminReplyAt", expression = "java(java.time.LocalDateTime.now())")
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "productId", ignore = true)
    @Mapping(target = "userId", ignore = true)
    @Mapping(target = "rating", ignore = true)
    @Mapping(target = "title", ignore = true)
    @Mapping(target = "comment", ignore = true)
    @Mapping(target = "isVerifiedPurchase", ignore = true)
    @Mapping(target = "likeCount", ignore = true)
    @Mapping(target = "dislikeCount", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    @Mapping(target = "deletedAt", ignore = true)
    void addAdminReply(@MappingTarget ProductReviewEntity entity, Long adminId, String reply);
    
    @Mapping(target = "adminReply", constant = "")
    @Mapping(target = "adminId", expression = "java(null)")
    @Mapping(target = "adminReplyAt", expression = "java(null)")
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "productId", ignore = true)
    @Mapping(target = "userId", ignore = true)
    @Mapping(target = "rating", ignore = true)
    @Mapping(target = "title", ignore = true)
    @Mapping(target = "comment", ignore = true)
    @Mapping(target = "isVerifiedPurchase", ignore = true)
    @Mapping(target = "likeCount", ignore = true)
    @Mapping(target = "dislikeCount", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    @Mapping(target = "deletedAt", ignore = true)
    void removeAdminReply(@MappingTarget ProductReviewEntity entity, ProductReview ignored);
    
    @Mapping(target = "likeCount", expression = "java(entity.getLikeCount() + 1)")
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "productId", ignore = true)
    @Mapping(target = "userId", ignore = true)
    @Mapping(target = "rating", ignore = true)
    @Mapping(target = "title", ignore = true)
    @Mapping(target = "comment", ignore = true)
    @Mapping(target = "isVerifiedPurchase", ignore = true)
    @Mapping(target = "dislikeCount", ignore = true)
    @Mapping(target = "adminReply", ignore = true)
    @Mapping(target = "adminReplyAt", ignore = true)
    @Mapping(target = "adminId", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    @Mapping(target = "deletedAt", ignore = true)
    void incrementLikeCount(@MappingTarget ProductReviewEntity entity, ProductReview ignored);
    
    @Mapping(target = "likeCount", expression = "java(Math.max(0, entity.getLikeCount() - 1))")
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "productId", ignore = true)
    @Mapping(target = "userId", ignore = true)
    @Mapping(target = "rating", ignore = true)
    @Mapping(target = "title", ignore = true)
    @Mapping(target = "comment", ignore = true)
    @Mapping(target = "isVerifiedPurchase", ignore = true)
    @Mapping(target = "dislikeCount", ignore = true)
    @Mapping(target = "adminReply", ignore = true)
    @Mapping(target = "adminReplyAt", ignore = true)
    @Mapping(target = "adminId", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    @Mapping(target = "deletedAt", ignore = true)
    void decrementLikeCount(@MappingTarget ProductReviewEntity entity, ProductReview ignored);
    
    @Mapping(target = "dislikeCount", expression = "java(entity.getDislikeCount() + 1)")
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "productId", ignore = true)
    @Mapping(target = "userId", ignore = true)
    @Mapping(target = "rating", ignore = true)
    @Mapping(target = "title", ignore = true)
    @Mapping(target = "comment", ignore = true)
    @Mapping(target = "isVerifiedPurchase", ignore = true)
    @Mapping(target = "likeCount", ignore = true)
    @Mapping(target = "adminReply", ignore = true)
    @Mapping(target = "adminReplyAt", ignore = true)
    @Mapping(target = "adminId", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    @Mapping(target = "deletedAt", ignore = true)
    void incrementDislikeCount(@MappingTarget ProductReviewEntity entity, ProductReview ignored);
    
    @Mapping(target = "dislikeCount", expression = "java(Math.max(0, entity.getDislikeCount() - 1))")
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "productId", ignore = true)
    @Mapping(target = "userId", ignore = true)
    @Mapping(target = "rating", ignore = true)
    @Mapping(target = "title", ignore = true)
    @Mapping(target = "comment", ignore = true)
    @Mapping(target = "isVerifiedPurchase", ignore = true)
    @Mapping(target = "likeCount", ignore = true)
    @Mapping(target = "adminReply", ignore = true)
    @Mapping(target = "adminReplyAt", ignore = true)
    @Mapping(target = "adminId", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    @Mapping(target = "deletedAt", ignore = true)
    void decrementDislikeCount(@MappingTarget ProductReviewEntity entity, ProductReview ignored);
}
